//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baka_MPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baka_MPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ajax_loader {
            get {
                object obj = ResourceManager.GetObject("ajax_loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.mp3; *.ogg; *.wav; *.wma; *.ac3; *.ape; *.flac; *.cue; *.thd; *.ra.
        /// </summary>
        internal static string AudioFiles {
            get {
                return ResourceManager.GetString("AudioFiles", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap default_next {
            get {
                object obj = ResourceManager.GetObject("default_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap default_open {
            get {
                object obj = ResourceManager.GetObject("default_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap default_pause {
            get {
                object obj = ResourceManager.GetObject("default_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap default_play {
            get {
                object obj = ResourceManager.GetObject("default_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap default_playlist {
            get {
                object obj = ResourceManager.GetObject("default_playlist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap default_previous {
            get {
                object obj = ResourceManager.GetObject("default_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap default_reverse {
            get {
                object obj = ResourceManager.GetObject("default_reverse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disabled_mic {
            get {
                object obj = ResourceManager.GetObject("disabled_mic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disabled_next {
            get {
                object obj = ResourceManager.GetObject("disabled_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disabled_pause {
            get {
                object obj = ResourceManager.GetObject("disabled_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disabled_play {
            get {
                object obj = ResourceManager.GetObject("disabled_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disabled_playlist {
            get {
                object obj = ResourceManager.GetObject("disabled_playlist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disabled_previous {
            get {
                object obj = ResourceManager.GetObject("disabled_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disabled_reverse {
            get {
                object obj = ResourceManager.GetObject("disabled_reverse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down_mic {
            get {
                object obj = ResourceManager.GetObject("down_mic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down_next {
            get {
                object obj = ResourceManager.GetObject("down_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down_open {
            get {
                object obj = ResourceManager.GetObject("down_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down_pause {
            get {
                object obj = ResourceManager.GetObject("down_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down_play {
            get {
                object obj = ResourceManager.GetObject("down_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down_playlist {
            get {
                object obj = ResourceManager.GetObject("down_playlist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down_previous {
            get {
                object obj = ResourceManager.GetObject("down_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down_reverse {
            get {
                object obj = ResourceManager.GetObject("down_reverse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap enabled_mic {
            get {
                object obj = ResourceManager.GetObject("enabled_mic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exists {
            get {
                object obj = ResourceManager.GetObject("exists", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_64 {
            get {
                object obj = ResourceManager.GetObject("icon_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] LCD {
            get {
                object obj = ResourceManager.GetObject("LCD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Music_128 {
            get {
                object obj = ResourceManager.GetObject("Music_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap not_exists {
            get {
                object obj = ResourceManager.GetObject("not_exists", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap repeat {
            get {
                object obj = ResourceManager.GetObject("repeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shuffle {
            get {
                object obj = ResourceManager.GetObject("shuffle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon tool_next {
            get {
                object obj = ResourceManager.GetObject("tool_next", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tool_pause {
            get {
                object obj = ResourceManager.GetObject("tool_pause", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tool_play {
            get {
                object obj = ResourceManager.GetObject("tool_play", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tool_previous {
            get {
                object obj = ResourceManager.GetObject("tool_previous", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.avi; *.vfx; *.divx; *.mpg; *.mpeg; *.m1v; *.m2v; *.mpv; *.dv; *.3gp; *.mov; *.mp4; *.m4v; *.mqv; *.dat; *.vcd; *.ogg; *.ogm; *.ogv; *.asf; *.wmv; *.vob; *.mkv; *.nsv; *.ram; *.flv; *.rm; *.ts; *.rmvb; *.dvr-ms; *.m2t; *.m2ts; *.rec; *.f4v; *.hdmov; *.webm; *.vp8.
        /// </summary>
        internal static string VideoFiles {
            get {
                return ResourceManager.GetString("VideoFiles", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap warning_blue_48 {
            get {
                object obj = ResourceManager.GetObject("warning_blue_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
